Feature/search storage.
Starlexxx/GoStudy pull request #4
Opened 2023-08-03 17:23 UTC by Starlexxx

Необходимо хранить и использовать результаты поиска:
* реализован механизм репозитория, который может искать и добавлять результаты;
* реализован репозиторий в виде текстового файла;
* добалено использование репозитория поисковик.

2023-08-07 06:52 UTC, DmitriyVTitov requested changes
Ответ на ДЗ должен быть полностью "зелёным". Я не могу разбираться с изменениями.

2023-08-19 07:41 UTC, DmitriyVTitov requested changes
Ответ на ДЗ должен быть полностью "зелёным". Я не могу разбираться с изменениями.
То есть надо создать отдельный каталог для ДЗ, поместить в него все файлы и всё добавить в pull request.
Все строчки кода должны быть зелёными (добавлениями).

2023-08-21 16:14 UTC, Starlexxx commented
> Ответ на ДЗ должен быть полностью "зелёным". Я не могу разбираться с изменениями. То есть надо создать отдельный каталог для ДЗ, поместить в него все файлы и всё добавить в pull request. Все строчки кода должны быть зелёными (добавлениями).

Извиняюсь, забыл удалить коммит из мастера (

2023-08-26 08:21 UTC, DmitriyVTitov approved these changes
ОК, но надо больше уделять внимания обработке ошибок.
Их нельзя игнорировать и не достаточно просто что-то напечатать.

2023-08-26 08:21 UTC, DmitriyVTitov commented on task4/GoWeb/cmd/goweb/goweb.go
> +		docs = append(docs, data...)
Ошибка игнорируется (печать на экран ничего не значит вообще)! Этого делать просто нельзя.
В стр.39 проверять нужно не результат, а ошибку.

2023-08-26 08:21 UTC, DmitriyVTitov commented on task4/GoWeb/cmd/goweb/goweb.go
> +	if searchWord != "" {
Опять ошибка игнорируется!

2023-08-26 08:21 UTC, DmitriyVTitov commented on task4/GoWeb/cmd/goweb/goweb.go
> +		}
Получается что не важно, была ли ошибка при сохранении документов ил нет - всё равно ищем.

2023-08-26 08:21 UTC, DmitriyVTitov commented on task4/GoWeb/pkg/index/storage/storage.go
> +}
Функция не может вернуть ошибку в принципе. Зачем она тогда в сигнатуре?

2023-08-28 09:35 UTC, merged